# Generated by Django 3.2 on 2021-04-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_pic', models.ImageField(blank='True', default='andaman.jpg', null=True, upload_to='')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], max_length=200, null=True)),
                ('nights', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('months', models.ManyToManyField(related_name='months', to='login.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag_pic', models.ImageField(blank='True', default='grouptour.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='login.Tag'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('day_pic', models.ImageField(blank='True', default='andaman.jpg', upload_to='')),
                ('dayno', models.IntegerField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.package')),
            ],
        ),
    ]
