# Generated by Django 3.2 on 2021-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='months',
            field=models.ManyToManyField(related_name='availmonths', to='login.Month'),
        ),
    ]
