# Generated by Django 3.2 on 2021-04-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
