# Generated by Django 3.2 on 2021-04-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_bookedtrips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookedtrips',
            new_name='Bookedtrip',
        ),
    ]
