# Generated by Django 3.2 on 2021-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_bookedtrips_bookedtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
