# Generated by Django 3.1.7 on 2021-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_prevtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevtrip',
            name='pack_pic',
            field=models.ImageField(blank='True', default='andaman.jpg', upload_to=''),
        ),
    ]
