# Generated by Django 3.1.7 on 2021-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_prevtrip_pack_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrip',
            name='pack_pic',
            field=models.ImageField(blank='True', default='andaman.jpg', upload_to=''),
        ),
    ]
