# Generated by Django 3.1.7 on 2021-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_bookedtrip_pack_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='wallet',
            name='live_bitcoin_price',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
