# Generated by Django 3.1.7 on 2021-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210418_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(default=0, max_length=500)),
                ('public_key', models.CharField(default=0, max_length=500)),
                ('address', models.CharField(default=0, max_length=500)),
                ('live_bitcoin_price', models.CharField(default=0, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='live_bitcoin_price',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='public_key',
        ),
    ]
