# Generated by Django 3.1.7 on 2021-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210418_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_key', models.CharField(default=0, max_length=500)),
                ('address', models.CharField(default=0, max_length=500)),
                ('category', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
