# Generated by Django 3.1.7 on 2021-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_transaction_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='public_key',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
