# Generated by Django 3.1.7 on 2021-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20210418_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='public_key',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
